env:
  es6: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:vitest/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 6
  sourceType: module
plugins:
  - "@typescript-eslint"
  - "vitest"
root: true
