name: Build and Deploy Azure Functions Application

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build-deploy-functions-app.yaml
      - .github/workflows/reusable-build-functions-app.yaml
      - .github/workflows/reusable-deploy-functions-app.yaml
      - functions**

jobs:
  use-build-functions-app-workflow:
    uses: ./.github/workflows/reusable-build-functions-app.yaml
    with:
      AZURE_FUNCTIONS: ${{ vars.AZURE_FUNCTIONS }}

  use-deploy-functions-app-workflow:
    needs: use-build-functions-app-workflow
    uses: ./.github/workflows/reusable-deploy-functions-app.yaml
    with:
      AZURE_AD_SP_CONTRIBUTOR_CLIENT_ID: ${{ vars.AZURE_AD_SP_CONTRIBUTOR_CLIENT_ID }}
      AZURE_FUNCTIONS: ${{ vars.AZURE_FUNCTIONS }}
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
    secrets:
      AZURE_AD_SP_CONTRIBUTOR_CLIENT_SECRET: ${{ secrets.AZURE_AD_SP_CONTRIBUTOR_CLIENT_SECRET }}
