name: Create Azure Resources

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/create-azure-resources.yaml
      - resources.bicep

jobs:
  create-resources:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Login Azure as Contributor
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ vars.AZURE_AD_SP_CONTRIBUTOR_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_AD_SP_CONTRIBUTOR_CLIENT_SECRET }}","subscriptionId":"${{ vars.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ vars.AZURE_TENANT_ID }}"}'

      - name: Create Azure Resource Group if Needed
        run: |
          az group create \
            -n ${{ vars.AZURE_RESOURCE_GROUP }} \
            -l ${{ vars.AZURE_LOCATION }}

      - name: Deploy Azure Resources
        run: |
          az deployment group create \
            --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} \
            --template-file resources.bicep \
            --parameters \
              apiConnAzureblobName=${{ vars.AZURE_API_CONNECTION_AZUREBLOB }} \
              functionsName=${{ vars.AZURE_FUNCTIONS }} \
              insightsName=${{ vars.AZURE_APPLICATION_INSIGHTS }} \
              location=${{ vars.AZURE_LOCATION }} \
              storageName=${{ vars.AZURE_STORAGE }}
