name: Run Lint and Test before Merging Pull Request

on:
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: "20.10.0"

permissions:
  checks: write
  pull-requests: write
  contents: write

jobs:
  lint-bicep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint Bicep
        uses: synergy-au/bicep-lint-action@v1.1
        with:
          analyse-all-files: "true"

  lint-ts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-tommer-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: ${{ runner.os }}-tommer-${{ hashFiles('**/package-lock.json') }}-

      - name: Lint Typescript
        uses: reviewdog/action-eslint@v1
        with:
          eslint_flags: "**/*.{ts,tsx}"
          fail_on_error: true
          filter_mode: file
          level: warning
          reporter: github-pr-review

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-tommer-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: ${{ runner.os }}-tommer-${{ hashFiles('**/package-lock.json') }}-

      - name: Find Current Pull Request
        uses: jwalton/gh-find-current-pr@v1.3.2
        id: findPr

      - name: Jest coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2.2.6
        with:
          prnumber: ${{ steps.findPr.outputs.number }}
