name: Deploy GitHub Pages (Reusable Workflow)

on: workflow_call

jobs:
  deploy-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Coverage Badges
        id: deployment
        uses: actions/deploy-pages@v4
