name: Build Azure Functions Application (Reusable Workflow)

on:
  workflow_call:
    inputs:
      AZURE_FUNCTIONS:
        required: true
        type: string
      NODE_VERSION:
        default: "20.10.0"
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Node ${{ inputs.NODE_VERSION }} Environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.NODE_VERSION }}

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-tommer-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: ${{ runner.os }}-tommer-${{ hashFiles('**/package-lock.json') }}-

      - name: Install dependencies
        run: |
          pushd functions
          npm ci
          popd

      - name: Build
        run: |
          pushd functions
          npm run build
          popd

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.AZURE_FUNCTIONS }}
          path: |
            functions/dist
            functions/host.json
            functions/package.json
            !functions/node_modules
