name: Build GitHub Pages and Azure Functions Application (Reusable Workflow)

on:
  workflow_call:
    inputs:
      FUNCTIONS_NAME:
        required: true
        type: string
      NODE_VERSION:
        default: "20.10.0"
        required: false
        type: string

jobs:
  build-pages-and-functions-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Node ${{ inputs.NODE_VERSION }} Environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.NODE_VERSION }}

      - name: Restore Cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-tommer-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: ${{ runner.os }}-tommer-${{ hashFiles('**/package-lock.json') }}-

      - name: Install Dependencies
        run: npm ci

      - name: Test
        run: npx vitest --coverage.enabled --coverage.reporter=json-summary

      - name: Create Coverage Badges
        uses: jaywcjlove/coverage-badges-cli@v1.2.5
        with:
          output: public/badges.svg
          source: coverage/coverage-summary.json

      - name: Upload Coverage Badges Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

      - name: Build
        run: npm run build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.FUNCTIONS_NAME }}
          path: |
            dist
            host.json
            package.json
            !node_modules
